### ISSUE TITLE
Bump to v1.0.0

### ISSUE THREAD

**Issue by Havvy** [felixge/node-dirty#48]
A lot of packages rely on Dirty, and no work has been done on it. Releasing v1.0.0 would be a useful gesture in showing that the package is stable.

**Comment by felixge** [comment]
Sure. https://github.com/felixge/node-dirty/commit/141f4ab665e1f7b89688b97480c07ab79483e4c1 - it's stable :tm: now :smile: !

**Comment by Havvy** [comment]
\o/
