### ISSUE TITLE
forEach returns previously deleted records as nulls

### ISSUE THREAD

**Issue by ackmanx** [felixge/node-dirty#54]
Is there a reason that forEach iterates over deleted records, passing null as the value?

**Comment by felixge** [comment]
IIRC that shouldn't happen.

**Comment by rhansen** [comment]
Iteration after deletion [has test coverage](https://github.com/felixge/node-dirty/blob/d7fb4d4ecf0cce144efa21b674965631a7955e61/test/test-api.js#L86-L105) and the tests are passing so I'm going to assume the problem is resolved.
